"""Per-agent spec assembly — K&A-grounded skill descriptions + per-skill learned guidance,
rendered both as the dashboard UI payload and as downloadable per-agent markdown, then
packed into one team zip.

Deterministic and offline: every skill description comes from the framework's official
Knowledge & Ability checklist (framework.get_ka), and learned guidance is parsed from the
`### Skill` blocks refine.py already appends under agent_final.md's anchor. No LLM calls
at build time — nothing is invented.

Two-track honesty (BUILD_GUIDE §0.5 / §7.5) is preserved end to end: execution-verified
learned guidance is labelled distinctly from the official K&A rubric, and a run role's
learned guidance is attached ONLY to that agent (never leaked onto a same-named skill in
another agent that was never executed).
"""
import pathlib, re, zipfile
import framework

ANCHOR = "## Learned skill guidance"


def parse_learned(spec_text):
    """Pull the per-skill '### Skill (required L2)\\n<guidance>' blocks refine.py appends
    under the anchor. Returns {skill_name_lower: guidance_text}. Empty if refine never ran."""
    out = {}
    if not spec_text or ANCHOR not in spec_text:
        return out
    tail = spec_text.split(ANCHOR, 1)[1]
    for m in re.finditer(r"^###\s+(.+?)(?:\s*\(required L\d+\))?\s*$\n(.*?)(?=^###\s|\Z)",
                         tail, re.M | re.S):
        name = m.group(1).strip().lower()
        body = m.group(2).strip()
        if body and body.lower() != "_none yet._":
            out[name] = body
    return out


def skill_rows(role, learned=None):
    """Rich per-skill rows for one role: dedup by code, K&A-grounded, guidance attached.
    Each row -> {nm, code, lvl, exec, prof, ka:[{item,kind}], guidance}."""
    learned = learned or {}
    seen, ded = set(), []
    for s in framework.get_skills(role):          # same code can repeat across sectors
        if s["code"] not in seen:
            seen.add(s["code"]); ded.append(s)
    exec_codes = {x["code"] for x in framework.select_executable(ded, k=99)}
    rows = []
    for s in ded:
        ka = framework.get_ka(s["code"], s["required_level"])
        rows.append({
            "nm": s["skill"], "code": s["code"], "lvl": s["required_level"],
            "exec": 1 if s["code"] in exec_codes else 0,
            "prof": ka["proficiency_description"],
            "ka": ka["items"],                              # [{item, kind}]
            "guidance": learned.get(s["skill"].lower(), ""),  # only real, execution-verified text
        })
    return rows


def _split_ka(items):
    know = [i["item"] for i in items if i["kind"] == "knowledge"]
    able = [i["item"] for i in items if i["kind"] == "ability"]
    other = [i["item"] for i in items if i["kind"] not in ("knowledge", "ability")]
    return know, able, other


def build_markdown(agent, rows, enrich_rec, generated_on):
    """One self-contained agent spec: role, skills table, K&A descriptions, learned guidance."""
    role = agent["role"]
    e = agent["enrichment_summary"]
    sb = e["salary_band"]
    enrich_rec = enrich_rec or {}
    md = [f"# Agent Specification — {role}", ""]
    md += [f"> Generated by AgentProof · SkillsFuture Skills Framework · {generated_on}  ",
           f"> Sector: {enrich_rec.get('sector', 'Infocomm Technology')} · "
           f"Stage {agent['stage']} · Squad: {agent.get('squad', '—')}", ""]

    md += ["## Role", ""]
    resp = enrich_rec.get("responsibilities_distilled") or []
    if resp:
        md.append("Distilled from live job postings:")
        md.append("")
        md += [f"- {r.strip()}" for r in resp]
        md.append("")
    md += [f"**Produces:** {agent.get('produces', '—')}  "]
    if agent.get("consumes"):
        md.append(f"**Consumes:** artifact from `{agent['consumes']}`  ")
    md += [f"**Salary band (SGD):** {sb['median']:,} median · up to {sb['high']:,}  ",
           f"**Sourcing:** {e['n_postings']} live posting(s) · {e['n_tools']} tools · "
           f"matched via {e['matched_via']}", ""]

    md += ["## Official required skills", "",
           "| Skill | Code | Level | Track |", "|---|---|---|---|"]
    for r in rows:
        md.append(f"| {r['nm']} | {r['code']} | L{r['lvl']} | "
                  f"{'executed' if r['exec'] else 'rubric'} |")
    md += ["",
           "_Executed skills are proven by running real code in isolated local subprocesses, "
           "graded against the official K&A rubric. Rubric skills are LLM-judged against the "
           "same checklist and are never blended with executed scores (two tracks, §7.5)._", ""]

    md += ["## Skill descriptions & learned guidance", ""]
    for r in rows:
        md.append(f"### {r['nm']} — required L{r['lvl']}  ·  `{r['code']}`  "
                  f"· {'✓ execution battery' if r['exec'] else '○ rubric'}")
        md.append("")
        if r["prof"]:
            md += [f"*{r['prof']}*", ""]
        know, able, other = _split_ka(r["ka"])
        for label, group in (("Knowledge (K&A rubric)", know),
                             ("Ability (K&A rubric)", able),
                             ("K&A rubric", other)):
            if group:
                md.append(f"**{label}:**")
                md += [f"- {g}" for g in group]
                md.append("")
        if r["guidance"]:
            md += [f"**Learned guidance — execution-verified:** {r['guidance']}", ""]
        else:
            md += ["**Learned guidance:** _none execution-verified yet — this skill is "
                   "rubric-assessed against the K&A checklist above._", ""]
    return "\n".join(md).rstrip() + "\n"


def build_team(team_manifest, enrichment, spec_text, generated_on,
               out_dir="team_specs", zip_name="agent_team_specs.zip"):
    """Write one markdown per agent + a compressed team zip. Returns
    {agents:[{id, role, md, sk}], zip, count}. `sk` is the rich UI row list."""
    learned = parse_learned(spec_text)
    d = pathlib.Path(out_dir)
    d.mkdir(exist_ok=True)
    agents_out, files = [], []
    for a in team_manifest["agents"]:
        # a run role's learned guidance belongs to THAT agent only — never leak the anchor's
        # execution-verified guidance onto a same-named-but-unexecuted skill elsewhere.
        lm = learned if a.get("anchor") else {}
        rows = skill_rows(a["role"], lm)
        md = build_markdown(a, rows, enrichment.get(a["enrichment_key"], {}), generated_on)
        fp = d / f"{a['id']}.md"
        fp.write_text(md)
        files.append(fp)
        agents_out.append({"id": a["id"], "role": a["role"], "md": md, "sk": rows})
    zip_path = pathlib.Path(zip_name)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for fp in files:
            z.write(fp, arcname=fp.name)
    return {"agents": agents_out, "zip": str(zip_path), "count": len(files)}
